### PR TITLE
Msvc testing

### PR DESCRIPTION
**Pull request by hjanetzek**

### CODE REVIEW

**Comment by lygstate** [comment]
Looks much more better for me:)

**Comment by lygstate** [comment]
I have a question, why squash the commits? And makes my work disappear.

**Comment by tallytalwar** [comment]
@lygstate As a rule we are following on the team, any new feature will be merged with a merged commit, and any fixups, small refactors will be squashed and merged. You will still be shown in the contributors and even though the commit is squashed, your name is still on the git "commit" history.

**Comment by tallytalwar** [comment]
@lygstate Also since we are using `tangram` branch of yaml-cpp as our submodule, it gets hard to figure out the contributors to the project. So your point taken, and in future we will try to merge without squashing any PR/commit contribution from an outside contributor. Thanks for all your work and support :D.

**Pull request merged**
